# Generated by Django 4.1 on 2022-08-12 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="заказ №")),
                ("usd_price", models.PositiveIntegerField(verbose_name="стоимость($)")),
                (
                    "ruble_price",
                    models.PositiveIntegerField(verbose_name="стоимость(rub)"),
                ),
                ("date", models.DateField(verbose_name="срок поставки")),
            ],
        ),
        migrations.CreateModel(
            name="RublePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_exchange_code",
                    models.CharField(
                        default="USD",
                        max_length=3,
                        verbose_name="Exchange Currency Code",
                    ),
                ),
                (
                    "exchange_date",
                    models.DateField(
                        default=datetime.date(2022, 8, 12), verbose_name="Exchange Date"
                    ),
                ),
                (
                    "exchange_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="Exchange Amount"
                    ),
                ),
            ],
        ),
    ]
