version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/run/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    links:
      - db:db
    networks:
      payment_task_network:
          aliases:
            - db
  db:
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db
    env_file:
      - ./.env.prod.db
    networks:
      payment_task_network:
        aliases:
          - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/run/staticfiles/
    depends_on:
      - web
    networks:
      payment_task_network:
        aliases:
          - nginx

volumes:
  postgres_data:
  static_volume:

networks:
  payment_task_network:
    driver: bridge