version: '3.8'
services:
  web:
    build: ./app
    command: sh -c "python manage.py loaddata fixtures.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
    depends_on:
      - database
  database:
    environment:
      POSTGRES_DB: payment_task_db
      POSTGRES_PASSWORD: payment_task_db_password_1
    image: 'postgres:14.1'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'pg_data:/var/lib/postgresql/data:rw'
volumes:
  pg_data: {}
