# Generated by Django 4.1b1 on 2022-07-04 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Account Activation status"
                    ),
                ),
                (
                    "is_frozen",
                    models.BooleanField(
                        default=False, verbose_name="Account frozen status"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Is Staff"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name (as shown in ID)", max_length=150
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        help_text="Middle name (as shown in ID)", max_length=150
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Surname (as shown in ID)", max_length=150
                    ),
                ),
                (
                    "surname_2",
                    models.CharField(
                        help_text="Surname (as shown in ID)", max_length=150
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=40)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=90)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="UserPic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "picture",
                    models.FileField(
                        blank=True,
                        default="default_pro_pic.jpeg",
                        null=True,
                        upload_to=user.models.user_directory_path,
                    ),
                ),
                ("thumb_picture", models.ImageField(blank=True, upload_to="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
