# Generated by Django 4.1b1 on 2022-07-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_phone_number_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number_2",
        ),
        migrations.RemoveField(
            model_name="user",
            name="surname_2",
        ),
    ]
