# Generated by Django 4.1rc1 on 2022-07-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_teacher_is_stuff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="is_stuff",
            new_name="is_staff",
        ),
    ]
