# Generated by Django 4.1rc1 on 2022-07-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_rename_is_stuff_teacher_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(blank=True, to="school.student"),
        ),
    ]
