# Generated by Django 4.1rc1 on 2022-07-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_class_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(
                default=1, max_length=64, unique=True, verbose_name="Phone Number"
            ),
            preserve_default=False,
        ),
    ]
