# Generated by Django 4.1rc1 on 2022-07-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_teacher_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="_class",
            new_name="student_class",
        ),
    ]
