# Generated by Django 4.1.1 on 2022-09-19 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.item",
            ),
            preserve_default=False,
        ),
    ]
