# Generated by Django 4.1b1 on 2022-07-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindevice",
            name="is_registered_2",
            field=models.BooleanField(default=False),
        ),
    ]
